# Generated by Django 4.0.3 on 2022-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='NotFound', max_length=100),
        ),
    ]
