# Generated by Django 4.0.3 on 2022-07-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='domain',
            field=models.CharField(default='NotFound', max_length=100),
        ),
    ]
