# Generated by Django 4.0.3 on 2022-07-27 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shop_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 13, 35, 9, 168060, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='productprice',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
