# Generated by Django 4.0.3 on 2022-07-30 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_price_productprice_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprice',
            name='new_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprice',
            name='old_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 8, 13, 21, 358103, tzinfo=utc)),
        ),
    ]
