# Generated by Django 4.0.3 on 2022-07-30 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_is_available_productprice_new_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 8, 32, 2, 289292, tzinfo=utc)),
        ),
    ]
